kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: langfuse-clickhouse-gateway
spec:
  gatewayClassName: gke-l7-rilb
  addresses:
    - type: NamedAddress
      value: langfuse-clickhouse-static-ip
  listeners:
    - name: clickhouse
      protocol: HTTP
      port: 80
